// Mock Restaurant Staff Data - ARRIS RESTAURANT HRMS
export const mockEmployees = [
    {
        id: 'emp-001',
        employeeId: 'ARR001',
        firstName: 'Rajesh',
        lastName: 'Kumar',
        email: 'rajesh.kumar@arris.com',
        phone: '+91 98765 43210',
        dateOfBirth: '1985-03-15',
        gender: 'male',
        maritalStatus: 'married',
        address: '45 MG Road, Khar West',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400052',
        nationality: 'Indian',
        department: 'Kitchen',
        designation: 'Executive Chef',
        site: 'ARRIS Downtown',
        joiningDate: '2020-06-15',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Amit Patel',
        annualCTC: 780000,
        bankName: 'HDFC Bank',
        accountNumber: '12345678901234',
        ifscCode: 'HDFC0001234',
    },
    {
        id: 'emp-002',
        employeeId: 'ARR002',
        firstName: 'Priya',
        lastName: 'Sharma',
        email: 'priya.sharma@arris.com',
        phone: '+91 98765 43211',
        dateOfBirth: '1990-07-22',
        gender: 'female',
        maritalStatus: 'single',
        address: '78 Hill Road, Bandra',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400050',
        nationality: 'Indian',
        department: 'Service',
        designation: 'Floor Manager',
        site: 'ARRIS Downtown',
        joiningDate: '2020-08-01',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Amit Patel',
        annualCTC: 540000,
        bankName: 'ICICI Bank',
        accountNumber: '23456789012345',
        ifscCode: 'ICIC0002345',
    },
    {
        id: 'emp-003',
        employeeId: 'ARR003',
        firstName: 'Amit',
        lastName: 'Patel',
        email: 'amit.patel@arris.com',
        phone: '+91 98765 43212',
        dateOfBirth: '1982-11-10',
        gender: 'male',
        maritalStatus: 'married',
        address: '12 Pedder Road',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400026',
        nationality: 'Indian',
        department: 'Management',
        designation: 'General Manager',
        site: 'ARRIS Downtown',
        joiningDate: '2020-06-01',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'CEO',
        annualCTC: 1200000,
        bankName: 'SBI',
        accountNumber: '34567890123456',
        ifscCode: 'SBIN0003456',
    },
    {
        id: 'emp-004',
        employeeId: 'ARR004',
        firstName: 'Sneha',
        lastName: 'Reddy',
        email: 'sneha.reddy@arris.com',
        phone: '+91 98765 43213',
        dateOfBirth: '1992-05-18',
        gender: 'female',
        maritalStatus: 'single',
        address: '23 Worli Sea Face',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400018',
        nationality: 'Indian',
        department: 'Cashier',
        designation: 'Head Cashier',
        site: 'ARRIS Downtown',
        joiningDate: '2021-01-15',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Amit Patel',
        annualCTC: 360000,
        bankName: 'Axis Bank',
        accountNumber: '45678901234567',
        ifscCode: 'UTIB0004567',
    },
    {
        id: 'emp-005',
        employeeId: 'ARR005',
        firstName: 'Arjun',
        lastName: 'Kapoor',
        email: 'arjun.kapoor@arris.com',
        phone: '+91 98765 43214',
        dateOfBirth: '1989-12-20',
        gender: 'male',
        maritalStatus: 'married',
        address: '34 Carter Road',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400050',
        nationality: 'Indian',
        department: 'Kitchen',
        designation: 'Sous Chef',
        site: 'ARRIS Downtown',
        joiningDate: '2020-07-20',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Rajesh Kumar',
        annualCTC: 540000,
        bankName: 'SBI',
        accountNumber: '78901234567890',
        ifscCode: 'SBIN0007890',
    },
    {
        id: 'emp-006',
        employeeId: 'ARR006',
        firstName: 'Pooja',
        lastName: 'Nair',
        email: 'pooja.nair@arris.com',
        phone: '+91 98765 43215',
        dateOfBirth: '1995-06-14',
        gender: 'female',
        maritalStatus: 'single',
        address: '67 SV Road',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400058',
        nationality: 'Indian',
        department: 'Service',
        designation: 'Senior Waiter',
        site: 'ARRIS Andheri',
        joiningDate: '2021-03-25',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Neha Kapoor',
        annualCTC: 300000,
        bankName: 'Axis Bank',
        accountNumber: '89012345678901',
        ifscCode: 'UTIB0008901',
    },
    {
        id: 'emp-007',
        employeeId: 'ARR007',
        firstName: 'Rahul',
        lastName: 'Verma',
        email: 'rahul.verma@arris.com',
        phone: '+91 98765 43216',
        dateOfBirth: '1987-04-30',
        gender: 'male',
        maritalStatus: 'married',
        address: '90 Andheri Link Road',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400053',
        nationality: 'Indian',
        department: 'Grill',
        designation: 'Grill Chef',
        site: 'ARRIS Andheri',
        joiningDate: '2021-03-20',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Rajesh Kumar',
        annualCTC: 420000,
        bankName: 'HDFC Bank',
        accountNumber: '90123456789012',
        ifscCode: 'HDFC0009012',
    },
    {
        id: 'emp-008',
        employeeId: 'ARR008',
        firstName: 'Neha',
        lastName: 'Kapoor',
        email: 'neha.kapoor@arris.com',
        phone: '+91 98765 43217',
        dateOfBirth: '1992-08-12',
        gender: 'female',
        maritalStatus: 'single',
        address: '12 Veera Desai Road',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400053',
        nationality: 'Indian',
        department: 'Service',
        designation: 'Floor Manager',
        site: 'ARRIS Andheri',
        joiningDate: '2021-04-01',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Amit Patel',
        annualCTC: 520000,
        bankName: 'ICICI Bank',
        accountNumber: '01234567890123',
        ifscCode: 'ICIC0000123',
    },
    {
        id: 'emp-009',
        employeeId: 'ARR009',
        firstName: 'Karthik',
        lastName: 'Nair',
        email: 'karthik.nair@arris.com',
        phone: '+91 98765 43218',
        dateOfBirth: '1986-02-28',
        gender: 'male',
        maritalStatus: 'married',
        address: '45 Turner Road',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400050',
        nationality: 'Indian',
        department: 'Management',
        designation: 'Assistant Manager',
        site: 'ARRIS Bandra',
        joiningDate: '2021-09-10',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Amit Patel',
        annualCTC: 660000,
        bankName: 'SBI',
        accountNumber: '12345098765432',
        ifscCode: 'SBIN0001234',
    },
    {
        id: 'emp-010',
        employeeId: 'ARR010',
        firstName: 'Divya',
        lastName: 'Iyer',
        email: 'divya.iyer@arris.com',
        phone: '+91 98765 43219',
        dateOfBirth: '1994-10-05',
        gender: 'female',
        maritalStatus: 'single',
        address: '89 Hiranandani Gardens',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400076',
        nationality: 'Indian',
        department: 'Cashier',
        designation: 'Cashier',
        site: 'ARRIS Bandra',
        joiningDate: '2022-01-05',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Karthik Nair',
        annualCTC: 300000,
        bankName: 'Axis Bank',
        accountNumber: '23450987654321',
        ifscCode: 'UTIB0002345',
    },
    {
        id: 'emp-011',
        employeeId: 'ARR011',
        firstName: 'Rohan',
        lastName: 'Gupta',
        email: 'rohan.gupta@arris.com',
        phone: '+91 98765 43220',
        dateOfBirth: '1996-03-19',
        gender: 'male',
        maritalStatus: 'single',
        address: '56 Palm Beach Road',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400703',
        nationality: 'Indian',
        department: 'Kitchen',
        designation: 'Commis Chef',
        site: 'ARRIS Downtown',
        joiningDate: '2022-02-15',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Rajesh Kumar',
        annualCTC: 280000,
        bankName: 'HDFC Bank',
        accountNumber: '34560987654321',
        ifscCode: 'HDFC0003456',
    },
    {
        id: 'emp-012',
        employeeId: 'ARR012',
        firstName: 'Sonal',
        lastName: 'Desai',
        email: 'sonal.desai@arris.com',
        phone: '+91 98765 43221',
        dateOfBirth: '1997-11-24',
        gender: 'female',
        maritalStatus: 'single',
        address: '78 Hill Road',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400050',
        nationality: 'Indian',
        department: 'Service',
        designation: 'Waiter',
        site: 'ARRIS Bandra',
        joiningDate: '2022-03-10',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Karthik Nair',
        annualCTC: 240000,
        bankName: 'ICICI Bank',
        accountNumber: '45670987654321',
        ifscCode: 'ICIC0004567',
    },
    {
        id: 'emp-013',
        employeeId: 'ARR013',
        firstName: 'Aditya',
        lastName: 'Khanna',
        email: 'aditya.khanna@arris.com',
        phone: '+91 98765 43222',
        dateOfBirth: '1999-01-20',
        gender: 'male',
        maritalStatus: 'single',
        address: '23 Marine Drive',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400020',
        nationality: 'Indian',
        department: 'Service',
        designation: 'Waiter',
        site: 'ARRIS Downtown',
        joiningDate: '2022-07-01',
        employmentType: 'part-time',
        status: 'active',
        reportingManager: 'Priya Sharma',
        annualCTC: 150000,
        bankName: 'SBI',
        accountNumber: '56780987654321',
        ifscCode: 'SBIN0005678',
    },
    {
        id: 'emp-014',
        employeeId: 'ARR014',
        firstName: 'Kavita',
        lastName: 'Jain',
        email: 'kavita.jain@arris.com',
        phone: '+91 98765 43223',
        dateOfBirth: '1993-07-15',
        gender: 'female',
        maritalStatus: 'married',
        address: '90 Nepean Sea Road',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400006',
        nationality: 'Indian',
        department: 'Cleaning',
        designation: 'Housekeeping Staff',
        site: 'ARRIS Downtown',
        joiningDate: '2021-05-15',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Amit Patel',
        annualCTC: 220000,
        bankName: 'Axis Bank',
        accountNumber: '67890987654321',
        ifscCode: 'UTIB0006789',
    },
    {
        id: 'emp-015',
        employeeId: 'ARR015',
        firstName: 'Manish',
        lastName: 'Shah',
        email: 'manish.shah@arris.com',
        phone: '+91 98765 43224',
        dateOfBirth: '1990-05-03',
        gender: 'male',
        maritalStatus: 'married',
        address: '12 Carmichael Road',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400026',
        nationality: 'Indian',
        department: 'Cleaning',
        designation: 'Cleaning Supervisor',
        site: 'ARRIS Downtown',
        joiningDate: '2020-09-01',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Amit Patel',
        annualCTC: 280000,
        bankName: 'HDFC Bank',
        accountNumber: '78900987654321',
        ifscCode: 'HDFC0007890',
    },
    {
        id: 'emp-016',
        employeeId: 'ARR016',
        firstName: 'Ritu',
        lastName: 'Agarwal',
        email: 'ritu.agarwal@arris.com',
        phone: '+91 98765 43225',
        dateOfBirth: '1991-12-11',
        gender: 'female',
        maritalStatus: 'married',
        address: '45 Altamount Road',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400026',
        nationality: 'Indian',
        department: 'Kitchen',
        designation: 'Kitchen Helper',
        site: 'ARRIS Andheri',
        joiningDate: '2022-04-14',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Rajesh Kumar',
        annualCTC: 200000,
        bankName: 'ICICI Bank',
        accountNumber: '89010987654321',
        ifscCode: 'ICIC0008901',
    },
    {
        id: 'emp-017',
        employeeId: 'ARR017',
        firstName: 'Nikhil',
        lastName: 'Choudhary',
        email: 'nikhil.choudhary@arris.com',
        phone: '+91 98765 43226',
        dateOfBirth: '1988-09-27',
        gender: 'male',
        maritalStatus: 'single',
        address: '67 Cuffe Parade',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400005',
        nationality: 'Indian',
        department: 'Grill',
        designation: 'Grill Chef',
        site: 'ARRIS Bandra',
        joiningDate: '2021-10-20',
        employmentType: 'full-time',
        status: 'active',
        reportingManager: 'Rajesh Kumar',
        annualCTC: 400000,
        bankName: 'SBI',
        accountNumber: '90120987654321',
        ifscCode: 'SBIN0009012',
    },
];

export default mockEmployees;
